intelligent cache for k8s service discovery
smallrye/smallrye-stork pull request #374
Opened 2022-09-30 10:33 UTC by aureamunoz

2022-09-30 10:47 UTC, aureamunoz commented
cc @manusa

2022-09-30 10:52 UTC, manusa approved these changes
The Fabric8 side of things LGTM :+1:

2022-10-02 14:08 UTC, cescoffier requested changes

2022-10-02 14:08 UTC, cescoffier commented on core/src/main/java/io/smallrye/stork/impl/CachingServiceDiscovery.java
> +        Uni<List<ServiceInstance>> least = Uni.createFrom().deferred(() -> fetchNewServiceInstances(this.lastResults)
`least` is not very meaningful here. I would have said something like `retrieval`.

2022-10-02 14:08 UTC, cescoffier commented on core/src/main/java/io/smallrye/stork/impl/CachingServiceDiscovery.java
> +    // Overridable by the provider
I would add a javadoc block explaining:

1. the default behavior + default property
2. it can be overriden

2022-10-02 14:08 UTC, cescoffier commented on docs/docs/service-discovery/custom-service-discovery.md
> +### Improving the caching strategy
```suggestion
### Customizing the caching strategy
```

2022-10-02 14:08 UTC, cescoffier commented on docs/docs/service-discovery/custom-service-discovery.md
> +Sometimes it can be useful to change this behaviour and customize the cache expiration strategy. For example, imagine you are using a backend service discovery where service instances can change very
Can you use a 1 line per sentence rule?

2022-10-03 12:06 UTC, cescoffier approved these changes

2022-10-03 12:07 UTC, merged