feature: implement knative service discovery
smallrye/smallrye-stork pull request #421
Opened 2022-11-28 17:55 UTC by aureamunoz

Fixes #402

2023-01-02 11:00 UTC, cescoffier requested changes

2023-01-09 14:34 UTC, aureamunoz commented on docs/docs/service-discovery/knative.md
> +This is done by creating an [Informer](https://www.javadoc.io/static/io.fabric8/kubernetes-client-api/6.1.1/io/fabric8/kubernetes/client/informers/SharedIndexInformer.html), similar to a [Watch](http
You mean that Knative SD shouldn't be cacheable?

2023-01-09 15:11 UTC, cescoffier commented on docs/docs/service-discovery/knative.md
> +This is done by creating an [Informer](https://www.javadoc.io/static/io.fabric8/kubernetes-client-api/6.1.1/io/fabric8/kubernetes/client/informers/SharedIndexInformer.html), similar to a [Watch](http
Actually, it must be cached, or we are going to do too many API calls. So ignore my comment (brain was in post-PTO mode)

2023-01-09 15:28 UTC, aureamunoz commented on docs/docs/service-discovery/knative.md
> +This is done by creating an [Informer](https://www.javadoc.io/static/io.fabric8/kubernetes-client-api/6.1.1/io/fabric8/kubernetes/client/informers/SharedIndexInformer.html), similar to a [Watch](http
No problem. Indeed, I ask myself same question when coding it. Also, I saw (if I recall correctly) that the knative service resource didn't change on different calls so it makes sense to cache it (the pod changes but not the kn-service which is the resources that stork is watching).

2023-01-09 15:46 UTC, aureamunoz commented on docs/docs/service-discovery/knative.md
> +
Done

2023-01-09 15:56 UTC, cescoffier approved these changes

2023-01-09 15:57 UTC, merged