Add doc for observability
smallrye/smallrye-stork pull request #673
Opened 2023-10-04 15:21 UTC by aureamunoz

2023-10-05 08:03 UTC, cescoffier requested changes

2023-10-05 08:03 UTC, cescoffier commented on docs/docs/observability.md
> +An `ObservationCollector` implementation needs to override the `create` method in order to provide an instance of StorkObservation.
```suggestion
An `ObservationCollector` implementation must override the `create` method to provide an instance of StorkObservation.
```

2023-10-05 08:03 UTC, cescoffier commented on docs/docs/observability.md
> +The next step is to initialize Stork with an `ObservableStorkInfrastructure` taking an instance of your ObservationCollector as parameter.
```suggestion
The next step is to initialize Stork with an `ObservableStorkInfrastructure`, taking an instance of your `ObservationCollector` as parameter.
```

2023-10-05 08:03 UTC, cescoffier commented on docs/docs/observability.md
> +Then, Stork will use your implementation to register metrics.
```suggestion
Then, Stork uses your implementation to register metrics.
```

2023-10-05 08:03 UTC, cescoffier commented on docs/docs/observability.md
> +
Too many empty lines.

2023-10-05 08:03 UTC, cescoffier commented on docs/docs/observability.md
> +Stork metrics are automatically enabled when using Stork together with Micrometer extension in a Quarkus application. Micrometer collects the metrics of the Rest or Grpc client using Stork.
```suggestion
Stork metrics are automatically enabled when using Stork together with the Micrometer extension in a Quarkus application. 
Micrometer collects the metrics of the rest clients and grpc clients using Stork, as well as when using the Stork API.
```

2023-10-05 08:03 UTC, cescoffier commented on docs/snippets/examples/AcmeObservationCollector.java
> +    };
Here mention what needs to happen in the implementation.
That's where you get the composite (terminal event)

2023-10-09 09:56 UTC, aureamunoz commented on docs/docs/observability.md
> +The `StorkObservation` registers times, discovered instances, the selected instance and failures by reacting to the lifecycle of a Stork event such us:
mmm...yes, I aggree. We can remove it and add it if we feel the need

2023-10-10 15:26 UTC, cescoffier requested changes
Some of my suggestions from the previous review have not been integrated. Any reason?

2023-10-10 15:26 UTC, cescoffier commented on docs/docs/observability.md
> +- start : Observation has been started. Begin time is registered. Happens when the `ObservationCollector#create()` method gets called.
Why didn't you integrate this change?

2023-10-10 15:26 UTC, cescoffier commented on docs/docs/observability.md
> +- service discovery success: a collection of instances has been successfully discovered for a service. End discovery time and number of instances are registered. Happens when the `StorkObservation#on
Why didn't you integrate this change?

2023-10-10 15:26 UTC, cescoffier commented on docs/docs/observability.md
> +- service discovery error: an error occurred when discovering service. End discovery time and failure cause are registered. Happens when the `StorkObservation#onServiceDiscoveryFailure` gets called.
Why didn't you integrate this change?

2023-10-10 15:26 UTC, cescoffier commented on docs/docs/observability.md
> +- service selection success: an instance has been successfully selected from the collection. End selection time and selected instance id are registered. Happens when the `StorkObservation#onServiceSe
Why didn't you integrate this change?

2023-10-10 15:26 UTC, cescoffier commented on docs/docs/observability.md
> +- service selection error: an error occurred during selecting the instance. End selection time and failure cause are registered. Happens when the `StorkObservation#onServiceSelectionFailure` gets cal
Why didn't you integrate this change?

2023-10-10 15:26 UTC, cescoffier commented on docs/docs/observability.md
> +- end: Observation has finished. Overall duration is registered. Happens when the `StorkObservation#onServiceSelectionSuccess` gets called.
Why didn't you integrate this change?

2023-10-10 15:26 UTC, cescoffier commented on docs/docs/observability.md
> +An `ObservationCollector` implementation needs to override the `create` method in order to provide an instance of StorkObservation.
Why didn't you integrate this change?

2023-10-11 08:24 UTC, aureamunoz commented
> Some of my suggestions from the previous review have not been integrated. Any reason?

They were hidden in the UI and I completely missed them. Looking at them now

2023-10-11 11:26 UTC, cescoffier approved these changes
LGTM!

Can you squash and merge?

2023-10-11 12:45 UTC, merged